# Generated by Django 4.2.2 on 2023-06-13 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('home_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_slide', models.CharField()),
                ('yt_link', models.CharField()),
            ],
        ),
    ]
