# Generated by Django 3.2.20 on 2023-08-22 08:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='TBL_AuditTrail',
            fields=[
                ('AuditTrail_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('AuditTrail_user', models.CharField(blank=True, default='', max_length=255)),
                ('AuditTrail_activity', models.CharField(blank=True, default='', max_length=255)),
                ('AuditTrail_date', models.DateField(auto_now_add=True, null=True)),
                ('AuditTrail_time', models.TimeField(auto_now_add=True, null=True)),
                ('AuditTrail_action', models.CharField(blank=True, default='', max_length=255)),
                ('AuditTrail_staff', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TBL_Careers',
            fields=[
                ('Careers_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Careers_title', models.CharField(blank=True, default='', max_length=255)),
                ('Careers_date', models.CharField(blank=True, default='', max_length=255)),
                ('Careers_image', models.ImageField(blank=True, default='no_img.jpg', null=True, upload_to='')),
                ('Careers_content', models.TextField(blank=True, default='')),
                ('Careers_status', models.CharField(blank=True, default='Deactivated', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TBL_Header',
            fields=[
                ('Header_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Header_name', models.CharField(blank=True, default=None, max_length=255)),
                ('Header_url', models.CharField(blank=True, default='', max_length=255)),
                ('Header_logo', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TBL_Home',
            fields=[
                ('Home_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Home_title', models.CharField(blank=True, default='', max_length=255)),
                ('Home_content', models.CharField(blank=True, default='', max_length=255)),
                ('Home_image', models.ImageField(blank=True, default='no_img.jpg', null=True, upload_to='')),
                ('Home_url', models.CharField(blank=True, default='', max_length=255)),
                ('Home_date', models.DateField(blank=True, null=True)),
                ('Home_status', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TBL_ProgramAndServicesType',
            fields=[
                ('ProgramAndServicestype_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ProgramAndServicestype_name', models.CharField(blank=True, default='', max_length=255)),
                ('ProgramAndServicestype_url', models.CharField(blank=True, default='', max_length=255)),
                ('ProgramAndServicestype_logoimage', models.ImageField(blank=True, default='no_img.jpg', null=True, upload_to='')),
                ('ProgramAndServicestype_logo', models.ImageField(blank=True, default='no_img.jpg', null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='TBL_PublicationsType',
            fields=[
                ('Publicationstype_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Publicationstype_name', models.CharField(blank=True, default='', max_length=255)),
                ('Publicationstype_url', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TBL_SatalliteOfficesType',
            fields=[
                ('SatalliteOfficestype_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('SatalliteOfficestype_name', models.CharField(blank=True, default='', max_length=255)),
                ('SatalliteOfficestype_url', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TBL_StoriesType',
            fields=[
                ('Storiestype_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Storiestype_name', models.CharField(blank=True, default='', max_length=255)),
                ('Storiestype_url', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TBL_WhoWeAreType',
            fields=[
                ('WhoWeAretype_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('WhoWeAretype_name', models.CharField(blank=True, default=None, max_length=255)),
                ('WhoWeAretype_url', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TBL_WhoWeAre',
            fields=[
                ('WhoWeAre_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('WhoWeAre_title', models.CharField(blank=True, default='', max_length=255)),
                ('WhoWeAre_content', models.TextField(blank=True, default='')),
                ('WhoWeAre_image', models.ImageField(blank=True, default='no_img.jpg', null=True, upload_to='')),
                ('WhoWeAre_status', models.TextField(blank=True, default='')),
                ('WhoWeAretype_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tbl_whowearetype')),
            ],
        ),
        migrations.CreateModel(
            name='TBL_Stories',
            fields=[
                ('Stories_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Stories_name', models.CharField(blank=True, default='', max_length=255)),
                ('Stories_title', models.CharField(blank=True, default='', max_length=255)),
                ('Stories_date', models.DateField(blank=True, null=True)),
                ('Stories_content', models.CharField(blank=True, default='', max_length=255)),
                ('Stories_image', models.ImageField(blank=True, default='no_img.jpg', null=True, upload_to='')),
                ('Stories_ytlink', models.CharField(blank=True, default='', max_length=255)),
                ('Stories_status', models.CharField(blank=True, default='Deactivated', max_length=255)),
                ('Storiestype_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tbl_storiestype')),
            ],
        ),
        migrations.CreateModel(
            name='TBL_SatalliteOffices',
            fields=[
                ('SatalliteOffices_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('SatalliteOffices_region', models.CharField(blank=True, default='', max_length=255)),
                ('SatalliteOffices_city', models.CharField(blank=True, default='', max_length=255)),
                ('SatalliteOffices_content', models.CharField(blank=True, default='', max_length=255)),
                ('SatalliteOffices_image', models.ImageField(blank=True, default='no_img.jpg', null=True, upload_to='')),
                ('SatalliteOffices_status', models.CharField(blank=True, default='Deactivated', max_length=255)),
                ('SatalliteOfficestype_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tbl_satalliteofficestype')),
            ],
        ),
        migrations.CreateModel(
            name='TBL_Publications',
            fields=[
                ('Publications_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Publications_name', models.CharField(blank=True, default='', max_length=255)),
                ('Publications_title', models.CharField(blank=True, default='', max_length=255)),
                ('Publications_content', models.TextField(blank=True, default='')),
                ('Publications_image', models.ImageField(blank=True, default='no_img.jpg', null=True, upload_to='')),
                ('Publications_file', models.FileField(blank=True, default='', null=True, upload_to='')),
                ('Publications_pubDate', models.DateField(blank=True, default='', null=True)),
                ('Publications_status', models.CharField(blank=True, default='Deactivated', max_length=255)),
                ('Publicationstype_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tbl_publicationstype')),
            ],
        ),
        migrations.CreateModel(
            name='TBL_ProgramAndServices',
            fields=[
                ('ProgramAndServices_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ProgramAndServices_title', models.CharField(blank=True, default='', max_length=255)),
                ('ProgramAndServices_content', models.CharField(blank=True, default='', max_length=255)),
                ('ProgramAndServices_image', models.ImageField(blank=True, default='no_img.jpg', null=True, upload_to='')),
                ('ProgramAndServices_status', models.CharField(blank=True, default='Deactivated', max_length=255)),
                ('ProgramAndServicestype_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tbl_programandservicestype')),
            ],
        ),
    ]
