# Generated by Django 4.2.2 on 2023-06-14 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('announcements_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField()),
                ('publishedDate', models.CharField()),
                ('ImgSrc', models.CharField()),
                ('description', models.CharField()),
            ],
        ),
        migrations.DeleteModel(
            name='Home',
        ),
    ]
