# Generated by Django 3.2.20 on 2023-08-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_home',
            name='Home_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
