# Generated by Django 3.2.20 on 2023-08-24 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_tbl_home_home_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_home',
            name='Home_url',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
