# Generated by Django 4.2.2 on 2023-06-14 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_announcements_delete_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='description',
            field=models.TextField(),
        ),
    ]
