# Generated by Django 4.2.2 on 2023-06-14 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_announcements_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Announcements',
        ),
    ]
