# Generated by Django 3.2.20 on 2023-08-24 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_tbl_home_home_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_home',
            name='Home_content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
