# Generated by Django 3.2.20 on 2023-08-24 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_tbl_home_home_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_home',
            name='Home_content',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
