# Generated by Django 3.2.20 on 2023-08-24 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_tbl_home_home_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_home',
            name='Home_status',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
