# Generated by Django 3.2.20 on 2023-08-24 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_tbl_home_home_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_publications',
            name='Publications_content',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
