# Generated by Django 3.2.20 on 2023-08-24 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_tbl_publications_publications_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_publications',
            name='Publications_title',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
