# Generated by Django 4.2.2 on 2023-06-14 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
