# Generated by Django 3.2.20 on 2023-08-24 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_tbl_publications_publications_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_stories',
            name='Stories_content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
