# Generated by Django 4.2.2 on 2023-06-14 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_announcements_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
