# Generated by Django 4.2.2 on 2023-06-15 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_discription_announcements_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TBL_Announcements',
        ),
        migrations.RemoveField(
            model_name='tbl_publications',
            name='Publicationstype_id',
        ),
        migrations.RemoveField(
            model_name='tbl_satalliteoffices',
            name='SatalliteOfficestype_id',
        ),
        migrations.RemoveField(
            model_name='tbl_stories',
            name='Storiestype_id',
        ),
        migrations.RemoveField(
            model_name='tbl_whoweare',
            name='WhoWeAretype_id',
        ),
        migrations.DeleteModel(
            name='TBL_ProgramAndServices',
        ),
        migrations.DeleteModel(
            name='TBL_ProgramAndServicesType',
        ),
        migrations.DeleteModel(
            name='TBL_Publications',
        ),
        migrations.DeleteModel(
            name='TBL_PublicationsType',
        ),
        migrations.DeleteModel(
            name='TBL_SatalliteOffices',
        ),
        migrations.DeleteModel(
            name='TBL_SatalliteOfficesType',
        ),
        migrations.DeleteModel(
            name='TBL_Stories',
        ),
        migrations.DeleteModel(
            name='TBL_StoriesType',
        ),
        migrations.DeleteModel(
            name='TBL_WhoWeAre',
        ),
        migrations.DeleteModel(
            name='TBL_WhoWeAreType',
        ),
    ]
