# Generated by Django 4.2.2 on 2023-06-15 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_tbl_announcements_tbl_programandservicestype_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TBL_ProgramAndServices',
        ),
        migrations.DeleteModel(
            name='TBL_ProgramAndServicesType',
        ),
    ]
