# Generated by Django 4.2.2 on 2023-06-15 06:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_delete_tbl_programandservices_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TBL_ProgramAndServicesType',
            fields=[
                ('ProgramAndServicestype_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ProgramAndServicestype_name', models.CharField()),
                ('ProgramAndServicestype_url', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='TBL_ProgramAndServices',
            fields=[
                ('ProgramAndServices_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ProgramAndServices_title', models.CharField()),
                ('ProgramAndServices_logo', models.CharField()),
                ('ProgramAndServices_content', models.CharField(blank=True, default='')),
                ('ProgramAndServices_image', models.CharField()),
                ('ProgramAndServicestype_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tbl_programandservicestype')),
            ],
        ),
    ]
