# Generated by Django 4.2.2 on 2023-06-15 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_tbl_programandservicestype_tbl_programandservices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_satalliteoffices',
            name='SatalliteOfficestype_id',
        ),
        migrations.RemoveField(
            model_name='tbl_stories',
            name='Storiestype_id',
        ),
        migrations.DeleteModel(
            name='TBL_Publications',
        ),
        migrations.DeleteModel(
            name='TBL_PublicationsType',
        ),
        migrations.DeleteModel(
            name='TBL_SatalliteOffices',
        ),
        migrations.DeleteModel(
            name='TBL_SatalliteOfficesType',
        ),
        migrations.DeleteModel(
            name='TBL_Stories',
        ),
        migrations.DeleteModel(
            name='TBL_StoriesType',
        ),
    ]
