# Generated by Django 4.2.2 on 2023-06-16 00:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_tbl_publicationstype_tbl_satalliteofficestype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TBL_Header',
            fields=[
                ('Header_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Header_name', models.CharField()),
                ('Header_url', models.CharField(blank=True, default='')),
            ],
        ),
    ]
