# Generated by Django 4.2.2 on 2023-06-16 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_tbl_whoweare'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TBL_WhoWeAre',
        ),
    ]
