# Generated by Django 4.2.2 on 2023-06-16 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_tbl_whoweare'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_header',
            name='Header_logo',
            field=models.CharField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tbl_programandservicestype',
            name='ProgramAndServicestype_logo',
            field=models.CharField(blank=True, default=''),
        ),
    ]
