# Generated by Django 4.2.2 on 2023-06-16 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_tbl_header_header_logo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_programandservicestype',
            old_name='ProgramAndServicestype_logo',
            new_name='ProgramAndServicestype_logoimage',
        ),
    ]
