# Generated by Django 4.2.2 on 2023-06-19 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_rename_programandservicestype_logo_tbl_programandservicestype_programandservicestype_logoimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_satalliteoffices',
            old_name='SatalliteOffices_logo',
            new_name='SatalliteOffices_city',
        ),
        migrations.RenameField(
            model_name='tbl_satalliteoffices',
            old_name='SatalliteOffices_title',
            new_name='SatalliteOffices_region',
        ),
    ]
