# Generated by Django 4.2.2 on 2023-06-19 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_rename_satalliteoffices_logo_tbl_satalliteoffices_satalliteoffices_city_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TBL_Publications',
        ),
    ]
