# Generated by Django 4.2.2 on 2023-06-19 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_tbl_publications'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TBL_Publications',
        ),
    ]
