# Generated by Django 4.2.2 on 2023-06-19 05:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_delete_tbl_publications'),
    ]

    operations = [
        migrations.CreateModel(
            name='TBL_Publications',
            fields=[
                ('Publications_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Publications_name', models.CharField()),
                ('Publications_title', models.CharField()),
                ('Publications_content', models.TextField(blank=True, default='')),
                ('Publications_image', models.CharField()),
                ('Publications_file', models.CharField()),
                ('Publicationstype_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tbl_publicationstype')),
            ],
        ),
    ]
