# Generated by Django 4.2.2 on 2023-06-19 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_tbl_publications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_publications',
            name='Publications_file',
            field=models.CharField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='tbl_publications',
            name='Publications_image',
            field=models.CharField(blank=True, default=''),
        ),
    ]
