# Generated by Django 4.2.2 on 2023-06-19 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_alter_tbl_publications_publications_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_publications',
            name='Publications_pubDate',
            field=models.CharField(blank=True, default=''),
        ),
    ]
