# Generated by Django 4.2.2 on 2023-06-20 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_alter_tbl_stories_stories_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_stories',
            name='Stories_name',
            field=models.CharField(blank=True, default=''),
        ),
    ]
