# Generated by Django 4.2.2 on 2023-06-20 02:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_tbl_stories_stories_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TBL_Careers',
            fields=[
                ('Careers_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Careers_title', models.CharField(blank=True, default='')),
                ('Announcements_date', models.CharField(blank=True, default='')),
                ('Careers_image', models.CharField(blank=True, default='')),
                ('Careers_content', models.TextField(blank=True, default='')),
            ],
        ),
    ]
