# Generated by Django 4.2.2 on 2023-06-20 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_tbl_careers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_careers',
            old_name='Announcements_date',
            new_name='Careers_date',
        ),
    ]
