# Generated by Django 4.2.2 on 2023-06-21 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_tbl_stories_stories_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_programandservices',
            name='ProgramAndServices_logo',
        ),
        migrations.AddField(
            model_name='tbl_programandservicestype',
            name='ProgramAndServices_logo',
            field=models.CharField(blank=True, default=''),
        ),
    ]
