# Generated by Django 4.2.2 on 2023-06-21 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_remove_tbl_programandservices_programandservices_logo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_programandservicestype',
            old_name='ProgramAndServices_logo',
            new_name='ProgramAndServicestype_logo',
        ),
    ]
