# Generated by Django 4.2.2 on 2023-06-21 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_rename_programandservices_logo_tbl_programandservicestype_programandservicestype_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_whoweare',
            name='WhoWeAre_image',
            field=models.CharField(blank=True, default='no_img.jpg'),
        ),
    ]
