# Generated by Django 4.2.2 on 2023-06-23 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_alter_tbl_whoweare_whoweare_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_publications',
            name='Publications_pubDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
