# Generated by Django 4.2.2 on 2023-06-23 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_alter_tbl_publications_publications_pubdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_publications',
            name='Publications_pubDate',
            field=models.DateField(blank=True, default='', null=True),
        ),
    ]
