# Generated by Django 4.2.2 on 2023-06-23 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_alter_tbl_publications_publications_pubdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Announcements',
        ),
        migrations.DeleteModel(
            name='TBL_Announcements',
        ),
    ]
