# Generated by Django 4.2.2 on 2023-06-23 06:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_delete_announcements_delete_tbl_announcements'),
    ]

    operations = [
        migrations.CreateModel(
            name='TBL_Home',
            fields=[
                ('Home_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Home_title', models.CharField(blank=True, default='')),
                ('Home_content', models.CharField(blank=True, default='')),
                ('Home_image', models.CharField(blank=True, default='')),
            ],
        ),
    ]
