# Generated by Django 4.2.2 on 2023-06-23 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_tbl_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_home',
            name='Home_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
