# Generated by Django 4.2.2 on 2023-07-06 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_home',
            name='Home_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
    ]
