# Generated by Django 4.2.2 on 2023-07-07 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_alter_tbl_home_home_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_whoweare',
            name='WhoWeAre_image',
            field=models.ImageField(blank=True, default='no_img.jpg', null=True, upload_to=''),
        ),
    ]
