# Generated by Django 4.2.2 on 2023-07-07 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_alter_tbl_whoweare_whoweare_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_whoweare',
            name='WhoWeAre_status',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
