# Generated by Django 4.2.2 on 2023-07-10 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_tbl_whoweare_whoweare_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_programandservices',
            name='ProgramAndServices_image',
            field=models.ImageField(blank=True, default='no_img.jpg', null=True, upload_to='ProgramAndServices/'),
        ),
    ]
