# Generated by Django 4.2.2 on 2023-07-10 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_alter_tbl_programandservices_programandservices_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_programandservicestype',
            name='ProgramAndServicestype_logo',
            field=models.ImageField(blank=True, default='no_img.jpg', null=True, upload_to='ProgramAndServices/'),
        ),
        migrations.AlterField(
            model_name='tbl_programandservicestype',
            name='ProgramAndServicestype_logoimage',
            field=models.ImageField(blank=True, default='no_img.jpg', null=True, upload_to='ProgramAndServices/'),
        ),
    ]
