# Generated by Django 4.2.2 on 2023-07-10 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_alter_tbl_programandservicestype_programandservicestype_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_programandservices',
            name='ProgramAndServices_image',
            field=models.ImageField(blank=True, default='no_img.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='tbl_programandservicestype',
            name='ProgramAndServicestype_logo',
            field=models.ImageField(blank=True, default='no_img.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='tbl_programandservicestype',
            name='ProgramAndServicestype_logoimage',
            field=models.ImageField(blank=True, default='no_img.jpg', null=True, upload_to=''),
        ),
    ]
