# Generated by Django 4.2.2 on 2023-07-10 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_alter_tbl_programandservices_programandservices_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_programandservices',
            name='ProgramAndServices_status',
            field=models.CharField(blank=True, default='Active', null=True),
        ),
    ]
