# Generated by Django 4.2.2 on 2023-07-11 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_alter_tbl_satalliteoffices_satalliteoffices_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_publications',
            name='Publications_status',
            field=models.CharField(blank=True, default='Active', null=True),
        ),
        migrations.AlterField(
            model_name='tbl_publications',
            name='Publications_image',
            field=models.ImageField(blank=True, default='no_img.jpg', null=True, upload_to=''),
        ),
    ]
