# Generated by Django 4.2.2 on 2023-07-11 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_alter_tbl_publications_publications_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_publications',
            name='Publications_file',
            field=models.FileField(blank=True, default='', null=True, upload_to=''),
        ),
    ]
