# Generated by Django 4.2.2 on 2023-07-11 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_alter_tbl_publications_publications_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_publications',
            name='Publications_name',
            field=models.CharField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='tbl_publications',
            name='Publications_title',
            field=models.CharField(blank=True, default='', null=True),
        ),
    ]
