# Generated by Django 4.2.2 on 2023-07-13 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0078_tbl_stories_stories_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_stories',
            name='Stories_status',
            field=models.CharField(blank=True, default='Deactivated', null=True),
        ),
    ]
