# Generated by Django 4.2.2 on 2023-07-13 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0079_alter_tbl_stories_stories_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_stories',
            name='Stories_ytlink',
            field=models.CharField(blank=True, default='', null=True),
        ),
    ]
