# Generated by Django 4.2.2 on 2023-07-14 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0080_alter_tbl_stories_stories_ytlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_careers',
            name='Careers_status',
            field=models.CharField(blank=True, default='Activate', null=True),
        ),
    ]
