# Generated by Django 4.2.2 on 2023-07-14 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0081_tbl_careers_careers_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_careers',
            name='Careers_status',
        ),
    ]
