# Generated by Django 4.2.2 on 2023-07-14 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0084_alter_tbl_careers_careers_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_careers',
            name='Careers_image',
            field=models.ImageField(blank=True, default='no_img.jpg', null=True, upload_to=''),
        ),
    ]
