# Generated by Django 4.2.2 on 2023-08-01 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0086_alter_tbl_whoweare_whoweare_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_whoweare',
            name='WhoWeAre_image',
            field=models.ImageField(blank=True, default='no_img.jpg', null=True, upload_to=''),
        ),
    ]
