# Generated by Django 4.2.2 on 2023-08-02 07:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0087_alter_tbl_whoweare_whoweare_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TBL_AuditTrail',
            fields=[
                ('AuditTrail_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('AuditTrail_user', models.CharField(blank=True, default='')),
                ('AuditTrail_activity', models.CharField(blank=True, default='')),
                ('AuditTrail_time', models.TimeField(blank=True, null=True)),
                ('AuditTrail_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
