# Generated by Django 4.2.2 on 2023-08-02 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0091_alter_tbl_audittrail_audittrail_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_audittrail',
            name='AuditTrail_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
