# Generated by Django 4.2.2 on 2023-08-02 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0092_tbl_audittrail_audittrail_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_audittrail',
            name='AuditTrail_time',
        ),
    ]
