# Generated by Django 4.2.2 on 2023-08-04 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0097_remove_tbl_audittrail_audittrail_action'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_audittrail',
            old_name='AuditTrail_activity',
            new_name='AuditTrail_action',
        ),
    ]
