# Generated by Django 4.2.2 on 2023-08-04 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0101_rename_audittrail_action_tbl_audittrail_audittrail_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_audittrail',
            name='AuditTrail_action',
            field=models.CharField(blank=True, default=''),
        ),
    ]
