# Generated by Django 4.2.2 on 2023-08-08 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0102_tbl_audittrail_audittrail_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_audittrail',
            name='AuditTrail_staff',
            field=models.CharField(blank=True, default=''),
        ),
    ]
