# Generated by Django 4.2.2 on 2023-08-31 03:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0103_tbl_audittrail_audittrail_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='TBL_Member',
            fields=[
                ('Member_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Member_username', models.CharField(blank=True, default='')),
                ('Member_password', models.CharField(blank=True, default='')),
            ],
        ),
        migrations.AlterField(
            model_name='tbl_home',
            name='Home_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_home',
            name='Home_image',
            field=models.ImageField(blank=True, default='no_img.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='tbl_home',
            name='Home_url',
            field=models.CharField(blank=True, default='', null=True),
        ),
    ]
