# Generated by Django 4.2.2 on 2023-08-31 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0104_tbl_member_alter_tbl_home_home_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_member',
            name='Member_username',
            field=models.CharField(blank=True, default='', unique=True),
        ),
    ]
