# Generated by Django 4.2.2 on 2023-09-06 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0105_alter_tbl_member_member_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_member',
            name='Member_admin',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='tbl_member',
            name='Member_firstname',
            field=models.CharField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tbl_member',
            name='Member_lastname',
            field=models.CharField(blank=True, default=''),
        ),
    ]
