# Generated by Django 4.2.2 on 2023-09-12 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0106_tbl_member_member_admin_tbl_member_member_firstname_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TBL_Member',
        ),
    ]
