# Generated by Django 4.2.2 on 2023-09-12 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0107_delete_tbl_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='TBL_Category',
            fields=[
                ('Category_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Category_name', models.CharField(blank=True, default='')),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TBL_Product',
            fields=[
                ('Product_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Product_title', models.CharField(blank=True, default='')),
                ('Category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tbl_category')),
            ],
        ),
    ]
