# Generated by Django 4.2.2 on 2023-09-12 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0108_tbl_category_tbl_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_product',
            name='Home_image',
            field=models.ImageField(blank=True, default='no_img.jpg', null=True, upload_to=''),
        ),
    ]
