# Generated by Django 4.2.2 on 2023-09-12 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0109_tbl_product_home_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_category',
            name='Category_name',
            field=models.CharField(blank=True, default='', unique=True),
        ),
    ]
