# Generated by Django 4.2.2 on 2023-09-12 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0110_alter_tbl_category_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_category',
            name='User_id',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Members'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
