# Generated by Django 4.2.2 on 2023-09-13 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0111_alter_tbl_category_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_product',
            old_name='Home_image',
            new_name='Product_image',
        ),
    ]
