# Generated by Django 4.2.2 on 2023-09-13 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0112_rename_home_image_tbl_product_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_product',
            name='Category_id',
        ),
        migrations.DeleteModel(
            name='TBL_Category',
        ),
        migrations.DeleteModel(
            name='TBL_Product',
        ),
    ]
