# Generated by Django 4.2.2 on 2023-09-13 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0114_tbl_category_tbl_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TBL_Category',
        ),
        migrations.DeleteModel(
            name='TBL_Product',
        ),
    ]
