# Generated by Django 4.2.2 on 2023-09-13 01:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0115_delete_tbl_category_delete_tbl_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='TBL_Category',
            fields=[
                ('Category_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Category_name', models.CharField(blank=True, default='', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TBL_Product',
            fields=[
                ('Product_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Product_image', models.ImageField(blank=True, default='no_img.jpg', null=True, upload_to='')),
                ('Product_title', models.CharField(blank=True, default='')),
                ('Category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tbl_category')),
                ('User_id', models.ForeignKey(limit_choices_to={'groups__name': 'Members'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
