# Generated by Django 4.2.2 on 2023-09-20 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0116_tbl_category_tbl_product'),
    ]

    operations = [
    ]
