# Generated by Django 4.2.2 on 2023-09-20 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0117_auto_20230920_0845'),
    ]

    operations = [
    ]
