# Generated by Django 4.2.2 on 2023-09-20 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0118_auto_20230920_0847'),
    ]

    operations = [
    ]
