# Generated by Django 4.2.2 on 2023-09-25 03:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0119_auto_20230920_0900'),
    ]

    operations = [
        migrations.CreateModel(
            name='TBL_Tag',
            fields=[
                ('Tag_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Tag_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='tbl_product',
            name='Tag',
            field=models.ManyToManyField(to='api.tbl_tag'),
        ),
    ]
