# Generated by Django 4.2.2 on 2023-10-04 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0121_tbl_product_created_at_tbl_product_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_product',
            name='Product_status',
            field=models.CharField(blank=True, default='Deactivated', null=True),
        ),
        migrations.AlterField(
            model_name='tbl_whoweare',
            name='WhoWeAre_status',
            field=models.TextField(blank=True, default='Deactivated', null=True),
        ),
    ]
