# Generated by Django 4.2.2 on 2023-10-04 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0122_tbl_product_product_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_product',
            name='Product_status',
            field=models.CharField(blank=True, default='Activated', null=True),
        ),
    ]
