# Generated by Django 4.2.2 on 2023-10-12 05:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0123_alter_tbl_product_product_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActivityLogs',
            fields=[
                ('AdminAuditTrail_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('AdminAuditTrail_user', models.CharField(blank=True, default='')),
                ('AdminAuditTrail_activity', models.CharField(blank=True, default='')),
                ('AdminAuditTrail_action', models.CharField(blank=True, default='')),
                ('AdminAuditTrail_date', models.DateField(auto_now_add=True, null=True)),
                ('AdminAuditTrail_time', models.TimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MemberAuditTrail',
            fields=[
                ('MemberAuditTrail_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('MemberAuditTrail_user', models.CharField(blank=True, default='')),
                ('MemberAuditTrail_activity', models.CharField(blank=True, default='')),
                ('MemberAuditTrail_action', models.CharField(blank=True, default='')),
                ('MemberAuditTrail_date', models.DateField(auto_now_add=True, null=True)),
                ('MemberAuditTrail_time', models.TimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='tbl_product',
            name='Product_status',
            field=models.CharField(blank=True, default='Active', null=True),
        ),
    ]
