# Generated by Django 4.2.2 on 2023-10-12 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0124_adminactivitylogs_memberaudittrail_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdminActivityLogs',
            new_name='AdminAuditTrail',
        ),
    ]
