# Generated by Django 4.2.2 on 2023-10-16 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0126_adminaudittrail_adminaudittrail_createdat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminaudittrail',
            name='AdminAuditTrail_createdAt',
        ),
        migrations.RemoveField(
            model_name='memberaudittrail',
            name='MemberAuditTrail_createdAt',
        ),
    ]
